apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://query-frontend:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
- name: Cortex
  type: prometheus
  access: proxy
  orgId: 1
  url: http://cortex:9009/api/prom
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
